spring:
  application:
    name: statistics-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://user:password@localhost:27017/statisticsdb}

security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:8080/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:8080/uaa/users/current

server:
  servlet:
    context-path: /statistics

rates:
  url: ${RATES_URL:http://exchange-rate:8080/exchangerates}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000