server:
  port: 7000

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:5000/uaa/oauth/token
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

rates:
  url: ${RATES_URL:http://localhost:8080/exchangerates}